### ISSUE TITLE
dev: Harmonize database errors in the Project

### ISSUE THREAD

**Issue by jbcaron** [madara-alliance/madara#169]
# dev: Harmonize database errors in the Project

## Description:
Currently, our project has multiple enums representing different types of errors for database:
- DeoxysStorageError
- DbError
- BonsaiDbError
- MappingDbError

Having multiple error enums can lead to inconsistency and increased complexity when handling errors across different modules. To improve maintainability and ease of use, we should harmonize these into a single unified error enum.

## Proposed Solution:
1. Create a unified error enum: Define a single enum, that encapsulates all possible database errors.
2. Refactor existing error enums: Modify existing code to use the unified AppError enum instead of the specific error enums.
3. Implement conversions: Implement From trait conversions to convert specific errors into `StarknetRpcApiError.
4. Update error handling: Ensure all error handling logic is updated to work with the unified error enum.

**Comment by Ophiase** [comment]
I'm not sure to understand.
Do you prefer the following solution :

```rust
#[derive(thiserror::Error, Debug)]
pub enum AppError {
    #[error("DB Error: {0}")]
    DbError(#[from] DbError),
    #[error("Bonsai DB Error: {0}")]
    BonsaiDbError(#[from] BonsaiDbError),
    #[error("Deoxys Storage Error: {0}")]
    DeoxysStorageError(#[from] DeoxysStorageError),
    #[error("Mapping DB Error: {0}")]
    MappingDbError(#[from] MappingDbError),
}
```

Or something like that :

```rust
#[derive(thiserror::Error, Debug)]
pub enum AppError {
    // FROM DBError
    #[error("Failed to commit DB Update: `{0}`")]
    RocksDB(#[from] rocksdb::Error),
    #[error("A value was queryied that was not initialized at column: `{0}` key: `{1}`")]
    ValueNotInitialized(Column, String),
    #[error("Format error: `{0}`")]
    Format(String),
    #[error("value codec error: {0}")]
    Bincode(#[from] bincode::Error),
    
    // FROM BonsaiDBError
    ...
    
    // FROM DeoxysStorageError
    ...
    
    // FROM MappingDBError
    ...
}
 ```

**Comment by jbcaron** [comment]
### Choosing Between `anyhow` and Adding Context to Errors

#### Context

Currently, our project uses several enums to represent database errors (`DbError`, `BonsaiDbError`, `DeoxysStorageError`). We need to harmonize these errors to simplify error handling and improve code maintainability. A key question is whether we should use the `anyhow` library for error management or explicitly add context to errors (e.g., including the column, query, etc.).

#### Proposed Options

1. **Use `anyhow` for All Errors**

   - **Advantages**:
     - Simplifies error handling using a single library for the entire project.
     - `anyhow` allows easy addition of context to errors via `.context()`.
     - Less boilerplate code to define and manage errors.
   
   - **Disadvantages**:
     - Less granular control over error types.
     - Can obscure specific error details, making debugging harder.

2. **Add Context to Errors**

   - **Advantages**:
     - Provides precise and detailed error control.
     - Facilitates debugging by providing specific error information (e.g., the involved column or query).
   
   - **Disadvantages**:
     - Requires more code to define and manage errors.
     - Can become verbose and complex with many error types.
   
3. **Use `anyhow` Only for Public Methods**

   - **Advantages**:
     - Combines the benefits of both approaches: simplicity for public methods and details for internal methods.
     - Public methods benefit from the simplicity of `anyhow`, while internal methods have detailed errors.
   
   - **Disadvantages**:
     - Adds complexity to the codebase with two error management approaches.
     - Can be confusing for developers, requiring a deep understanding of the error usage rules.
   
#### Discussion

We need to choose one of these options based on our needs for error management, maintainability, and code simplicity. Here are some questions to consider:

- What level of error detail do we need for debugging?
- Do we prefer a uniform approach for all errors or a distinction between public and internal methods?
- What is the priority between code simplicity and error information granularity?

Your feedback and suggestions are welcome to make an informed decision.

---
