### ISSUE TITLE
feat(sequencer): Add full/sequencing support in Deoxys

### ISSUE THREAD

**Issue by antiyro** [madara-alliance/madara#188]
### Is there an existing issue?

- [X] I have searched the existing issues

### Motivation

Currently, our codebase contains all the necessary elements to synchronize the state of Starknet in read mode via the feeder gateway. As part of our code swap with Madara's codebase, we need to accommodate a second mode, which is the block creation mode (sequencing).

### Request

The goal is to configure our codebase to use the `--full` parameter (for full node client mode) or the `--authority` parameter (for sequencer mode) where necessary.

1. **Full Node Mode (`--full`):**
   - This mode should enable synchronization via the feeder gateway (or via p2p in the future).
   - It should create its state from block 0 or from a snapshot set up using the `--snap` parameter.

2. **Sequencer Mode (`--authority`):**
   - This mode should disable synchronization via the feeder gateway.
   - It should produce blocks at a defined interval (block time) starting from an empty genesis block, using transactions invoked by the following methods:
     - [`starknet_addInvokeTransaction`](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_write_api.json#L11)
     - [`starknet_addDeclareTransaction`](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_write_api.json#L67)
     - [`starknet_addDeployAccountTransaction`](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_write_api.json#L144)
   - These methods should also be configured to either forward information to the feeder gateway (`--full`) or to the transaction pool of the running sequencer (`--authority`).

Additionally, when using the `--authority` parameter, L1-L2 messaging and subsequent events supported by Madara-Orchestrator should also be activated.

### Are you willing to help with this request?

Yes!

**Comment by cchudant** [comment]
Update on sequencing: #217 is going to get merged soon with basic block production, but in an experimental state
Tests and fixes are coming afterward, but here are the few features that are missing besides fixes:

- save mempool with rocksdb to avoid dropping txs on restart
- support continuing a pending block from restart
- finish the configurable chain config :)
- mempool size limits
- optimistic parallelism (just a flag to activate on blockifier)
- devnet tooling, more generally
