### ISSUE TITLE
feat(metrics): Replace influx db + change compose accordingly

### ISSUE THREAD

**Issue by antiyro** [madara-alliance/madara#193]
### Is there an existing issue?

- [X] I have searched the existing issues

### Motivation

Currently one of our metric internaly is our storage usage using InfluxDB to track the base-path size. It uses a lot of spaces and it's not portable for users.

This metric is an array of storage(gb)/time:

![Capture d’écran 2024-07-03 à 11 01 30](https://github.com/KasarLabs/deoxys/assets/74653697/1bcfa449-2073-46e7-b067-24c36b33ac63)

### Request

We would like to implement a native check of this base-path to ensure we get the appropriate size.

### Solution

One solution would be to do a simple system call (`du -sh`) plus parsing and serve it to the prometheus endpoint.

Feel free to challenge this solution bellow this issue.

### Are you willing to help with this request?

Yes!

**Comment by Trantorian1** [comment]
This pr is no longer relevant since our migration to opentelemetry for metrics

**Comment by Trantorian1** [comment]
This pr is no longer relevant since our migration to opentelemetry for metrics
