### ISSUE TITLE
fix(class): Fix the current class hash computation implementation

### ISSUE THREAD

**Issue by antiyro** [madara-alliance/madara#210]
### Is there an existing issue?

- [X] I have searched the existing issues

### Motivation

Currently, we skip the verification of class hashes in the codebase because it does not match the current verification on the mainnet for a portion of the state. The existing implementation for computing class hashes, located [here](https://github.com/KasarLabs/deoxys/blob/main/crates/primitives/class/src/class_hash.rs), is heavily inspired by the Pathfinder implementation, which can be found [here](https://github.com/eqlabs/pathfinder/blob/main/crates/gateway-types/src/class_hash.rs#L180).

### Request

The goal is to:
1. Uncomment the code at this [location](https://github.com/KasarLabs/deoxys/blob/main/crates/client/sync/src/utils/convert.rs#L236) to trigger class verification, ensuring it works for all Cairo 0 classes on the mainnet.
2. Subsequently, compute the Sierra classes, which should be simpler due to their more generic computation requirements.

### Solution

1. First, uncomment the specified code to enable the class verification process.
2. Verify that this change allows the system to correctly process and verify all Cairo 0 classes on the mainnet.
3. Once Cairo 0 class verification is functioning correctly, implement the computation for Sierra classes.

It is recommended to test these changes by running Madara in full node mode to synchronize via the FGW.

### Are you willing to help with this request?

Yes!

**Comment by jbcaron** [comment]
***Mismatched class hash at block 20726***
```
Mismatched class hash, received 0x371b5f7c5517d84205365a87f02dcef230efa7b4dd91a9e4ba7e04c5b69d69b; computed 0x19fc0e011a6de8ecbabecf88303d305ec485f0e08993eec5df62fccac1a135e
 ```
