### ISSUE TITLE
feat(clean): dc_db: rename DbBlockId::BlockN to DbBlockId::Number

### ISSUE THREAD

**Issue by cchudant** [madara-alliance/madara#217]
Lifted from @tdelabro's review comment in #198

DbBlockId::BlockN should be renamed DbBlockId::Number in dc_db so that it reads better

**Comment by Jeanmichel7** [comment]
I don't have a lot of experience, I'm new to this project, but I'd like to try it if possible.

**Comment by varun-doshi** [comment]
I'd like to take this up
