### ISSUE TITLE
feat(ci): workflow for release

### ISSUE THREAD

**Issue by jbcaron** [madara-alliance/madara#250]
### Is there an existing issue?

- [X] I have searched the existing issues

### Motivation

We need an action workflow to automate the release

### Request

This workflow should handle: 
- automatically create a release on GitHub when a tag is pushed
- update documentation

### Are you willing to help with this request?

Yes!

**Comment by cchudant** [comment]
I think we should try [cargo-dist](https://github.com/axodotdev/cargo-dist) :)

**Comment by antiyro** [comment]
Reviving this issue to tell the following path that was decided internally:

- Merge [this PR](https://github.com/madara-alliance/madara/pull/281) to upgrade docker
- Merge [Adel fix ](https://github.com/madara-alliance/madara/pull/281)on ChainConfigs
- Merge a workflow to build a docker image on each releases
- Release v0.7.0

**Comment by antiyro** [comment]
done in #290
