### ISSUE TITLE
feat(tests): starknet js compatibility tests

### ISSUE THREAD

**Issue by apoorvsadana** [madara-alliance/madara#270]
### Is there an existing issue?

- [X] I have searched the existing issues

### Description of bug

We should have some test cases that test compatibility with starknetjs. Basic transfers, declares and deploys. We already were using this - https://github.com/ocdbytes/madara-scripts. We can do a few changes and integrate this with Madara.

**Comment by ikemHood** [comment]
Hello @apoorvsadana , I would love to work on this

**Comment by Trantorian1** [comment]
This has been resolved as of #284
