### ISSUE TITLE
fix(fgw): adapt FeePayment conversion for ConfirmedReceipt (gateway) based on tx version

### ISSUE THREAD

**Issue by jbcaron** [madara-alliance/madara#385]
### Is there an existing issue?

- [X] I have searched the existing issues

### Description of bug

Currently, the conversion of Felt to FeePayment defaults the PriceUnit to Wei:
```rust
impl From<Felt> for FeePayment {
    fn from(fee: Felt) -> Self {
        Self { amount: fee, unit: PriceUnit::Wei }
    }
}
```

however, the correct PriceUnit (either Wei or Fri) depends on the TransactionVersion, which is not directly accessible in the receipt structure. This leads to potential mismatches in fee representation for gateway receipts

the FeePayment conversion should dynamically determine the correct PriceUnit based on the tx version associated with the transaction that produced the receipt

**Comment by cchudant** [comment]
yes this From impl is confusing, it shouldnt exist imo
