### ISSUE TITLE
bug: Madara fails to sync block `20732` because of Legacy contract deserialization

### ISSUE THREAD

**Issue by notlesh** [madara-alliance/madara#396]
### Is there an existing issue?

- [X] I have searched the existing issues

### Description of bug

While trying to sync mainnet with Madara, I found that sync fails on block `20732` when it attempts to request class `0x371b5f7c5517d84205365a87f02dcef230efa7b4dd91a9e4ba7e04c5b69d69b`.

Error (not very helpful):

```
The provider has returned an error: Error serializing request: invalid type: null, expected a sequence, retrying in 6s
```

Specifically, it fails when trying to convert to a `LegacyContractClass` via `serde_json::from_value` [here](https://github.com/madara-alliance/madara/blob/faeeea8fd3daf7fc9ce710c5f0c9ec7d50e2e354/crates/client/gateway/client/src/methods.rs#L104).

If we print the value it's attempting to use, we see that it has a `null` for `abi`:

```json
{"abi":null,"entry_points_by_type":{"CONSTRUCTOR" ...
```

Which I'm guessing is why it fails.

### Steps to reproduce

Sync mainnet with Madara up to block `20732`, e.g.:

```bash
cargo run --release \
    -- \
    --name Madara \
    --full \
    --base-path "../somewhere" \
    --network mainnet \
    --l1-endpoint "<redacted>"
```

**Comment by antiyro** [comment]
This PR should solve it https://github.com/madara-alliance/madara/pull/394. Tell me if it works.

**Comment by notlesh** [comment]
> This PR should solve it #394. Tell me if it works.

Confirmed that it is fixed. Thanks!
